"""
Django settings for {{ project_name }} project.

Generated by 'django-admin startproject' using Django {{ django_version }}.

For more information on this file, see
https://docs.djangoproject.com/en/{{ docs_version }}/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/{{ docs_version }}/ref/settings/
"""

import os

try:
    DEPLOY_TARGET = os.environ['DEPLOY_TARGET']
except KeyError:
    DEPLOY_TARGET = 'development'

if DEPLOY_TARGET == 'development':
    IN_DEVELOPMENT = True
else:
    IN_DEVELOPMENT = False


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Base Domain Name. App urls will be built from this.
BASE_DOMAIN = 'stmo.co'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/{{ docs_version }}/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '{{ secret_key }}'

# SECURITY WARNING: don't run with debug turned on in production!
if IN_DEVELOPMENT:
    DEBUG = True
else:
    DEBUG = False

ALLOWED_HOSTS = []
INTERNAL_IPS = ['127.0.0.1']

# Time Formats - Designed to play nice with Jinja2, not so much Django Templates
DATE_FORMAT = 'MMM DD, YYYY'
SHORT_DATE_FORMAT = 'DD/MM/YYYY'
DATETIME_FORMAT = 'MMM DD, YYYY, hh:mm a'
SHORT_DATETIME_FORMAT = 'DD/MM/YYYY hh:mm a'
TIME_FORMAT = 'h:m a'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django_jinja',
    'haystack',
    'rest_framework',
]

django-haystack
django-allauth
django-hijack
django-redis


if IN_DEVELOPMENT:
    INSTALLED_APPS += [
                        'django.contrib.staticfiles',
                        'debug_toolbar',
                      ]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if IN_DEVELOPMENT:
    MIDDLEWARE_CLASSES += ['debug_toolbar.middleware.DebugToolbarMiddleware', ]

ROOT_URLCONF = '{{ project_name }}.urls'

TEMPLATES = [
    {
        'NAME': 'jinja2',
        'BACKEND': 'django_jinja.backend.Jinja2',
        'DIRS': [os.path.join(BASE_DIR, 'jinja2/')],
        'APP_DIRS': True,
        'OPTIONS': {
            # 'match_extension': '.j2',
            # 'match_regex': r'.*\.j2$',
            'auto_reload': DEBUG,
        },
    },
    {
        'NAME': 'django',
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '{{ project_name }}.wsgi.application'


# Database
# https://docs.djangoproject.com/en/{{ docs_version }}/ref/settings/#databases

if IN_DEVELOPMENT:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': '{{ project_name }}',
            'USER': 'django',
            'PASSWORD': 'password',
            'HOST': 'db',
            'PORT': '',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/{{ docs_version }}/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/{{ docs_version }}/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/{{ docs_version }}/howto/static-files/
if IN_DEVELOPMENT:
    STATIC_URL = '/static/'
else:
    STATIC_URL = 'https://static.{{ project_name }}.{}/'.format(BASE_DOMAIN)

STATICFILES_DIRS = [os.path.join(BASE_DIR, '../static')]
STATIC_ROOT = os.path.join(BASE_DIR, '../../static')

# Media Files
if IN_DEVELOPMENT:
    MEDIA_URL = '/media/'
else:
    MEDIA_URL = 'https://media.{{ project_name }}.{}/'.format(BASE_DOMAIN)
MEDIA_ROOT = os.path.join(BASE_DIR, '../../media')

# Haystack
# https://django-haystack.readthedocs.io/en/v2.5.0/index.html
if IN_DEVELOPMENT:
    HAYSTACK_CONNECTIONS = {
        'default': {
            'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
            'PATH': os.path.join(os.path.dirname(__file__), 'whoosh_index'),
        },
    }
    HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
else:
    HAYSTACK_CONNECTIONS = {
        'default': {
            'ENGINE': 'haystack.backends.elasticsearch_backend.ElasticsearchSearchEngine',
            'URL': 'http://es:9200/',
            'INDEX_NAME': '{{ project_name }}',
        },
    }

# REST Framework
# See http://www.django-rest-framework.org/api-guide/settings/ for more settings
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}
